# claims-management-app/qa/values-qa.yaml
domainName: "domian-testing-claims"
env: "qa"
#configMapName: "domian-claims-management-app-cm"

# artifact details - Jenkins updates these
artifactName: "claims-management-qa-v1.0.0.bpmn"
artifactSha256: "changing qa artifact again"
artifactUrl: "https://nexus/claims/qa/v1.0.0.bpmn"

# job config
#jobName: "domian-claims-bpmn-sync-job"
image: "alpine:3.20"
ttlSecondsAfterFinished: 400
activeDeadlineSeconds: 600
backoffLimit: 1
secretName: "qa-secret"
