# claims-management-app/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: single-bpmn-ns-new                    # ← single shared namespace, same for all envs

helmCharts:
  - name: bpmn-sync-chart          # ← same chart for ALL domains
    repo: http://nexus-nexus-repository-manager.default.svc.cluster.local:8081/repository/helm-hosted/
    version: 0.1.0
    releaseName: claims-dev        # ← domain + env scoped
    valuesFile: values-claims-dev.yaml    # ← domain specific overrides