# apps/claims-parent.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: domain-chart-app-claims-parent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/selflearner2025/generic-chart-repo-pattern.git
    targetRevision: test
    path: apps
    directory:
      include: "claims-*.yaml"     # ← only picks up claims child apps
      exclude: "*-parent.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true