# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configMapName }}-{{ .Values.env }}"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  artifactName: {{ .Values.artifactName | quote }}
  artifactSha256: {{ .Values.artifactSha256 | quote }}
  artifactUrl: {{ .Values.artifactUrl | quote }}